version: "3.9"
services:
  # DB起動には以下のコマンド実行が必要
  # sudo chmod 777 ./docker/dynamodb
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - dynamodb-local
      - user-account-manager
      - carbon-deposit-management

  dynamodb-admin:
    container_name: test_dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-local

  user-account-manager:
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    build: 
      context: ./user-account-management
      dockerfile: Dockerfile.dev
    ports:
      - "50051:50051"
    networks:
      - user-account-manager
    volumes:
      - ./user-account-management:/usr/src/user-account-management
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
      USERS_NAME: 'users'
      LOCALSTACK: true

  carbon-deposit-manager:
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    build:
      context: ./carbon-deposit-management
      dockerfile: Dockerfile.dev
    ports:
      - "50052:50052"
    networks:
      - carbon-deposit-management
    volumes:
      - ./carbon-deposit-management:/usr/src/carbon-deposit-management
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'
      CARBONDEPOSITS_NAME: 'carbon-deposits'
      LOCALSTACK: true

networks:
  dynamodb-local:
  user-account-manager:
  carbon-deposit-management: