version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    networks:
      - user-account-manager
      - user-co2-manager
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - user-account-manager
      - user-co2-manager
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo-user

  user-account-manager:
    build: ./user-account-management
    ports:
      - "50051:50051"
    networks:
      - user-account-manager
    volumes:
      - ./user-account-management:/usr/src/user-account-management
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example

  user-co2-manager:
    build: ./user-co2-management
    ports:
      - "50052:50052"
    networks:
      - user-co2-manager
    volumes:
      - ./user-co2-management:/usr/src/user-co2-management
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example

networks:
  user-account-manager:
  user-co2-manager: