version: "3.9"
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - user-account-manager

  user-account-manager:
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    build: 
      context: ./user-account-management
      dockerfile: Dockerfile.dev
    ports:
      - "50051:50051"
    networks:
      - user-account-manager
    volumes:
      - ./user-account-management:/usr/src/user-account-management
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_REGION: 'eu-west-1'

  user-co2-manager:
    build:
      context: ./user-co2-management
      dockerfile: Dockerfile.dev
    ports:
      - "50052:50052"
    networks:
      - user-co2-manager
    volumes:
      - ./user-co2-management:/usr/src/user-co2-management

networks:
  user-account-manager:
  user-co2-manager: