FROM rust:1.66.0

WORKDIR /usr/src/user-co2-management

RUN apt update && apt upgrade -y
RUN apt install -y protobuf-compiler libprotobuf-dev
RUN cargo install cargo-watch

CMD ["cargo", "watch", "-x", "'run'"]