FROM rust:1.66.0

WORKDIR /usr/src/user-account-management

RUN apt update && apt upgrade -y
RUN apt install -y protobuf-compiler libprotobuf-dev

COPY . .
RUN cargo install --path .

CMD ["user-account-management"]